#!/usr/bin/env python3
"""Mirror repository Markdown documentation into a cloned GitHub Wiki repository."""

from __future__ import annotations

import os
import shutil
from pathlib import Path


ROOT = Path.cwd()
WIKI_DIR = ROOT / "wiki-repo"
DOCS_DIR = ROOT / "docs"
PAGES_BASE_URL = os.environ["PAGES_BASE_URL"].rstrip("/")


def wiki_title(stem: str) -> str:
    """Convert a repository docs filename stem into a GitHub Wiki page title."""

    parts = stem.replace("_", "-").split("-")
    return "-".join(part[:1].upper() + part[1:] for part in parts if part)


def copy_if_present(source: Path, destination: Path) -> bool:
    """Copy a file when it exists and return whether it was copied."""

    if not source.exists():
        return False
    shutil.copyfile(source, destination)
    return True


def remove_existing_markdown_pages() -> None:
    """Remove generated Markdown pages from the local Wiki clone."""

    for page in WIKI_DIR.glob("*.md"):
        page.unlink()


def mirror_repository_docs() -> list[tuple[str, str]]:
    """Mirror README, PLAN, and docs/*.md into the Wiki clone."""

    copied_docs: list[tuple[str, str]] = []

    copy_if_present(ROOT / "README.md", WIKI_DIR / "Home.md")
    copy_if_present(ROOT / "PLAN.md", WIKI_DIR / "Compiler-Upgrade-Plan.md")

    if DOCS_DIR.exists():
        for source in sorted(DOCS_DIR.glob("*.md")):
            title = wiki_title(source.stem)
            shutil.copyfile(source, WIKI_DIR / f"{title}.md")
            copied_docs.append((title.replace("-", " "), title))

    return copied_docs


def write_sidebar(copied_docs: list[tuple[str, str]]) -> None:
    """Generate the GitHub Wiki sidebar."""

    lines = [
        "# NovaLanguage",
        "",
        "- [Home](Home)",
        "- [Compiler Upgrade Plan](Compiler-Upgrade-Plan)",
        "",
        "## Documentation",
        "",
    ]

    lines.extend(f"- [{label}]({target})" for label, target in copied_docs)

    lines.extend(
        [
            "",
            "## API",
            "",
            f"- [Generated Javadoc]({PAGES_BASE_URL}/javadoc/)",
            "",
        ]
    )

    (WIKI_DIR / "_Sidebar.md").write_text("\n".join(lines), encoding="utf-8")


def write_api_reference() -> None:
    """Generate a small Wiki page pointing to the generated Javadoc."""

    content = f"""# API Reference

The generated Javadoc is published automatically from the `main` branch.

- [Open generated Javadoc]({PAGES_BASE_URL}/javadoc/)

The Javadoc is generated by GitHub Actions from the current Java sources and deployed through GitHub Pages.
"""

    (WIKI_DIR / "API-Reference.md").write_text(content, encoding="utf-8")


def main() -> None:
    if not WIKI_DIR.exists():
        raise SystemExit("wiki-repo directory does not exist. Clone the Wiki before running this script.")

    remove_existing_markdown_pages()
    copied_docs = mirror_repository_docs()
    write_sidebar(copied_docs)
    write_api_reference()


if __name__ == "__main__":
    main()
