#!/usr/bin/env python3
"""Sync issue-form scheduling metadata into GitHub Project date fields."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from dataclasses import dataclass
from datetime import date
from typing import Any

API_URL = os.environ.get("GITHUB_API_URL", "https://api.github.com")
GRAPHQL_URL = os.environ.get("GITHUB_GRAPHQL_URL", "https://api.github.com/graphql")
PROJECT_OWNER = os.environ.get("PROJECT_OWNER", "LucaPrevi0o")
PROJECT_NUMBER = int(os.environ.get("PROJECT_NUMBER", "4"))
START_DATE_FIELD = os.environ.get("PROJECT_START_DATE_FIELD", "Start date")
END_DATE_FIELD = os.environ.get("PROJECT_END_DATE_FIELD", "End date")
NO_RESPONSE = "_No response_"

SCHEDULE_FIELD_ALIASES = {
    "expected start": "Expected start",
    "start date": "Expected start",
    "starting date": "Expected start",
    "expected deadline": "Expected deadline",
    "deadline": "Expected deadline",
    "end date": "Expected deadline",
    "finish date": "Expected deadline",
    "target date": "Expected deadline",
}


class ProjectScheduleError(RuntimeError):
    """Raised when schedule metadata cannot be synchronized safely."""


@dataclass(frozen=True)
class Issue:
    """GitHub issue data needed by schedule sync."""

    number: int
    node_id: str
    title: str
    body: str


@dataclass(frozen=True)
class ProjectField:
    """GitHub Project field metadata."""

    id: str
    name: str


@dataclass(frozen=True)
class Project:
    """GitHub Project metadata used by schedule sync."""

    id: str
    title: str
    fields: dict[str, ProjectField]


class GitHubClient:
    """Small GitHub REST/GraphQL client backed by the workflow token."""

    def __init__(self, token: str) -> None:
        if not token:
            raise ProjectScheduleError(
                "Missing GitHub token. Set PROJECT_TOKEN with project write access, or provide GITHUB_TOKEN "
                "for read-only repository access."
            )
        self.token = token

    def rest(self, method: str, path: str, payload: dict[str, Any] | None = None) -> Any:
        """Call the GitHub REST API."""

        url = f"{API_URL.rstrip('/')}/{path.lstrip('/')}"
        data = json.dumps(payload).encode("utf-8") if payload is not None else None
        request = urllib.request.Request(
            url,
            data=data,
            method=method,
            headers={
                "Accept": "application/vnd.github+json",
                "Authorization": f"Bearer {self.token}",
                "X-GitHub-Api-Version": "2022-11-28",
                "User-Agent": "NovaLanguage-project-schedule-sync",
            },
        )
        return self._open_json(request)

    def graphql(self, query: str, variables: dict[str, Any] | None = None) -> Any:
        """Call the GitHub GraphQL API."""

        request = urllib.request.Request(
            GRAPHQL_URL,
            data=json.dumps({"query": query, "variables": variables or {}}).encode("utf-8"),
            method="POST",
            headers={
                "Accept": "application/vnd.github+json",
                "Authorization": f"Bearer {self.token}",
                "User-Agent": "NovaLanguage-project-schedule-sync",
            },
        )
        response = self._open_json(request)
        errors = response.get("errors")
        if errors:
            messages = "; ".join(error.get("message", str(error)) for error in errors)
            raise ProjectScheduleError(messages)
        return response["data"]

    def _open_json(self, request: urllib.request.Request) -> Any:
        try:
            with urllib.request.urlopen(request) as response:
                content = response.read().decode("utf-8")
        except urllib.error.HTTPError as error:
            detail = error.read().decode("utf-8")
            raise ProjectScheduleError(f"GitHub API {error.code}: {detail}") from error
        if not content:
            return None
        return json.loads(content)


def token_from_environment() -> str:
    """Return the best token available to the workflow."""

    return os.environ.get("PROJECT_TOKEN") or os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN", "")


def normalize_key(value: str) -> str:
    """Normalize a metadata heading for matching."""

    return re.sub(r"\s+", " ", value.strip().lower())


def form_field_value(lines: list[str]) -> str | None:
    """Return the first non-empty value from an issue-form field body."""

    value = "\n".join(lines).strip()
    if not value or value == NO_RESPONSE:
        return None
    return value.splitlines()[0].strip()


def parse_issue_form_schedule(body: str) -> dict[str, str]:
    """Parse schedule metadata from Markdown generated by GitHub issue forms."""

    metadata: dict[str, str] = {}
    current_heading: str | None = None
    current_lines: list[str] = []
    heading_pattern = re.compile(r"^###\s+(.+?)\s*$")

    def flush_current_field() -> None:
        if current_heading is None:
            return
        field_name = SCHEDULE_FIELD_ALIASES.get(normalize_key(current_heading))
        if field_name is None:
            return
        value = form_field_value(current_lines)
        if value:
            metadata[field_name] = value

    for line in body.splitlines():
        heading_match = heading_pattern.match(line)
        if heading_match:
            flush_current_field()
            current_heading = heading_match.group(1).strip()
            current_lines = []
            continue
        if current_heading is not None:
            current_lines.append(line)

    flush_current_field()
    return metadata


def parse_legacy_schedule(body: str) -> dict[str, str]:
    """Parse schedule metadata from legacy Project metadata blocks."""

    metadata: dict[str, str] = {}
    in_block = False
    header_pattern = re.compile(r"^##\s+(.+?)\s*$")
    item_pattern = re.compile(r"^-\s*([^:]+):\s*(.*?)\s*$")

    for line in body.splitlines():
        header_match = header_pattern.match(line)
        if header_match:
            heading = header_match.group(1).strip()
            if heading == "Project metadata":
                in_block = True
                continue
            if in_block:
                break
        if not in_block:
            continue
        item_match = item_pattern.match(line)
        if not item_match:
            continue
        field_name = SCHEDULE_FIELD_ALIASES.get(normalize_key(item_match.group(1)))
        value = item_match.group(2).strip()
        if field_name and value and value != NO_RESPONSE:
            metadata[field_name] = value

    return metadata


def parse_schedule(body: str) -> dict[str, str]:
    """Parse schedule metadata from supported issue body formats."""

    metadata = parse_legacy_schedule(body)
    metadata.update(parse_issue_form_schedule(body))
    return metadata


def iso_date(value: str, field_name: str) -> str:
    """Validate and normalize a YYYY-MM-DD date value."""

    try:
        parsed = date.fromisoformat(value.strip())
    except ValueError as error:
        raise ProjectScheduleError(f"{field_name} must use YYYY-MM-DD format, got '{value}'") from error
    return parsed.isoformat()


def normalized_schedule(metadata: dict[str, str]) -> dict[str, str]:
    """Return validated schedule values keyed by Project date field name."""

    schedule: dict[str, str] = {}
    start = metadata.get("Expected start")
    deadline = metadata.get("Expected deadline")

    if start:
        schedule[START_DATE_FIELD] = iso_date(start, "Expected start")
    if deadline:
        schedule[END_DATE_FIELD] = iso_date(deadline, "Expected deadline")

    if START_DATE_FIELD in schedule and END_DATE_FIELD in schedule:
        if date.fromisoformat(schedule[START_DATE_FIELD]) > date.fromisoformat(schedule[END_DATE_FIELD]):
            raise ProjectScheduleError("Expected start must not be later than Expected deadline")

    return schedule


def get_issue(client: GitHubClient, repository: str, number: int) -> Issue:
    """Fetch one issue through the REST API."""

    payload = client.rest("GET", f"/repos/{repository}/issues/{number}")
    if "pull_request" in payload:
        raise ProjectScheduleError(f"#{number} is a pull request, not an issue")
    return Issue(
        number=payload["number"],
        node_id=payload["node_id"],
        title=payload["title"],
        body=payload.get("body") or "",
    )


def list_open_issues(client: GitHubClient, repository: str) -> list[int]:
    """Return all open issue numbers for one repository."""

    numbers: list[int] = []
    page = 1
    while True:
        payload = client.rest("GET", f"/repos/{repository}/issues?state=open&per_page=100&page={page}")
        if not payload:
            return numbers
        numbers.extend(issue["number"] for issue in payload if "pull_request" not in issue)
        page += 1


def get_project(client: GitHubClient) -> Project:
    """Fetch the configured user-owned Project and its fields."""

    data = client.graphql(
        """
        query($owner: String!, $number: Int!) {
          user(login: $owner) {
            projectV2(number: $number) {
              id
              title
              fields(first: 50) {
                nodes {
                  ... on ProjectV2FieldCommon {
                    id
                    name
                  }
                }
              }
            }
          }
        }
        """,
        {"owner": PROJECT_OWNER, "number": PROJECT_NUMBER},
    )
    project_data = data["user"]["projectV2"]
    if project_data is None:
        raise ProjectScheduleError(f"Project {PROJECT_OWNER}/{PROJECT_NUMBER} was not found")

    fields: dict[str, ProjectField] = {}
    for node in project_data["fields"]["nodes"]:
        if node is None:
            continue
        fields[node["name"]] = ProjectField(node["id"], node["name"])

    return Project(project_data["id"], project_data["title"], fields)


def project_item_id(client: GitHubClient, project: Project, issue: Issue) -> str | None:
    """Return the Project item ID for an issue, if it is already in the Project."""

    data = client.graphql(
        """
        query($issueId: ID!) {
          node(id: $issueId) {
            ... on Issue {
              projectItems(first: 50, includeArchived: true) {
                nodes {
                  id
                  project {
                    id
                  }
                }
              }
            }
          }
        }
        """,
        {"issueId": issue.node_id},
    )
    for node in data["node"]["projectItems"]["nodes"]:
        if node["project"]["id"] == project.id:
            return node["id"]
    return None


def add_issue_to_project(client: GitHubClient, project: Project, issue: Issue) -> str:
    """Add an issue to the Project and return the Project item ID."""

    existing = project_item_id(client, project, issue)
    if existing:
        return existing

    data = client.graphql(
        """
        mutation($projectId: ID!, $contentId: ID!) {
          addProjectV2ItemById(input: { projectId: $projectId, contentId: $contentId }) {
            item {
              id
            }
          }
        }
        """,
        {"projectId": project.id, "contentId": issue.node_id},
    )
    return data["addProjectV2ItemById"]["item"]["id"]


def set_date_value(client: GitHubClient, project: Project, item_id: str, field: ProjectField, value: str) -> None:
    """Set one Project date field value."""

    client.graphql(
        """
        mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $date: Date!) {
          updateProjectV2ItemFieldValue(input: {
            projectId: $projectId,
            itemId: $itemId,
            fieldId: $fieldId,
            value: { date: $date }
          }) {
            projectV2Item {
              id
            }
          }
        }
        """,
        {
            "projectId": project.id,
            "itemId": item_id,
            "fieldId": field.id,
            "date": value,
        },
    )


def sync_issue_schedule(client: GitHubClient, repository: str, issue_number: int, strict: bool) -> bool:
    """Sync one issue's schedule metadata into Project date fields."""

    issue = get_issue(client, repository, issue_number)
    metadata = parse_schedule(issue.body)
    schedule = normalized_schedule(metadata)

    if not schedule:
        message = f"#{issue.number} has no Expected start or Expected deadline metadata; skipping schedule sync"
        if strict:
            raise ProjectScheduleError(message)
        print(f"::notice::{message}")
        return False

    project = get_project(client)
    item_id = add_issue_to_project(client, project, issue)

    for field_name, value in schedule.items():
        field = project.fields.get(field_name)
        if field is None:
            raise ProjectScheduleError(
                f"Project field '{field_name}' was not found. "
                "Create the date field in the roadmap Project or adjust PROJECT_START_DATE_FIELD/PROJECT_END_DATE_FIELD."
            )
        set_date_value(client, project, item_id, field, value)
        print(f"Synced #{issue.number}: {field_name} = {value}")

    return True


def sync_schedule_command(args: argparse.Namespace) -> int:
    """Run schedule synchronization."""

    client = GitHubClient(token_from_environment())
    if args.all_open and args.issue_number is not None:
        raise ProjectScheduleError("Provide --issue-number or --all-open, not both")
    if args.all_open:
        issue_numbers = list_open_issues(client, args.repo)
    elif args.issue_number is not None:
        issue_numbers = [args.issue_number]
    else:
        raise ProjectScheduleError("Provide --issue-number or --all-open")

    failures = 0
    for number in issue_numbers:
        try:
            sync_issue_schedule(client, args.repo, number, args.strict)
        except ProjectScheduleError as error:
            failures += 1
            print(f"::error::Failed to sync schedule for #{number}: {error}")
            if args.strict:
                break

    return 1 if failures else 0


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY"), help="Repository in owner/name form")
    parser.add_argument("--issue-number", type=int, help="Issue number to sync")
    parser.add_argument("--all-open", action="store_true", help="Sync every open issue with schedule metadata")
    parser.add_argument("--strict", action="store_true", help="Fail on missing or invalid schedule metadata")
    return parser


def main() -> int:
    """Run the schedule sync command."""

    parser = build_parser()
    args = parser.parse_args()
    if not args.repo:
        parser.error("--repo is required when GITHUB_REPOSITORY is not set")
    try:
        return sync_schedule_command(args)
    except ProjectScheduleError as error:
        print(f"::error::{error}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
