#!/usr/bin/env python3
"""GitHub Project automation helpers for NovaLanguage."""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import quote

from project_github import (
    GitHubClient,
    Issue,
    Project,
    ProjectAutomationError,
    ProjectField,
    ProjectIssueItem,
    ProjectItem,
    get_issue,
    get_pull_request,
    list_all_issues,
    list_closed_issues,
    list_open_issues,
    repository_parts,
    token_from_environment,
)
from project_metadata import (
    ACTIVE_STATUSES,
    DONE_STATUS,
    HIGH_PRIORITY,
    LEGACY_KIND_FIELD,
    LEGACY_PHASE_FIELD,
    MANAGED_KIND_LABELS,
    METADATA_HEADER,
    NO_RESPONSE,
    PHASE_NUMBER_TO_MILESTONE,
    PRIORITY_ALIASES,
    PRIORITY_FIELD,
    SHARED_PHASE_MILESTONES,
    SIZE_FIELD,
    STATUS_ALIASES,
    STATUS_FIELD,
)


PROJECT_OWNER = os.environ.get("PROJECT_OWNER", "LucaPrevi0o")
PROJECT_NUMBER = int(os.environ.get("PROJECT_NUMBER", "4"))
PROJECT_TITLE = os.environ.get("PROJECT_TITLE", "Nova - Development Roadmap")

STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "between", "by", "can", "from",
    "has", "in", "into", "is", "it", "keep", "later", "of", "or", "should",
    "that", "the", "to", "with", "work",
}

ISSUE_FORM_FIELD_ALIASES = {
    "priority": "Priority",
    "size": "Size",
    "suggested status": "Suggested status",
    "area": "Area",
}

LEGACY_NATIVE_BODY_FIELD_ALIASES = {
    "milestone": "Milestone",
    "labels": "Kind",
    "label": "Kind",
    "kind": "Kind",
}


@dataclass(frozen=True)
class LegacyMetadataFinding:
    """One issue that still carries metadata migration markers."""

    issue: Issue
    reasons: tuple[str, ...]


def legacy_metadata_block_fields(body: str) -> dict[str, str]:
    """Return fields from a legacy Project metadata block for migration audits."""

    metadata: dict[str, str] = {}
    in_block = False
    header_pattern = re.compile(r"^##\s+(.+?)\s*$")
    item_pattern = re.compile(r"^-\s*([^:]+):\s*(.*?)\s*$")

    for line in body.splitlines():
        header_match = header_pattern.match(line)
        if header_match:
            heading = header_match.group(1).strip()
            if heading == METADATA_HEADER:
                in_block = True
                continue
            if in_block:
                break

        if not in_block:
            continue

        item_match = item_pattern.match(line)
        if item_match:
            metadata[item_match.group(1).strip()] = item_match.group(2).strip()

    return metadata


def form_field_value(field_name: str, lines: list[str]) -> str | None:
    """Return one metadata value from an issue-form field body."""

    checked_values: list[str] = []
    saw_checkbox = False
    for line in lines:
        checkbox = re.match(r"^-\s*\[([ xX])\]\s*(.+?)\s*$", line)
        if not checkbox:
            continue
        saw_checkbox = True
        if checkbox.group(1).lower() == "x":
            checked_values.append(checkbox.group(2).strip())

    if checked_values:
        return " / ".join(checked_values)
    if saw_checkbox and field_name == "Kind":
        return None

    value = "\n".join(lines).strip()
    if not value or value == NO_RESPONSE:
        return None
    return value.splitlines()[0].strip()


def parse_issue_form_metadata(body: str) -> dict[str, str]:
    """Parse metadata from Markdown generated by GitHub issue forms."""

    metadata: dict[str, str] = {}
    current_heading: str | None = None
    current_lines: list[str] = []
    heading_pattern = re.compile(r"^###\s+(.+?)\s*$")

    def flush_current_field() -> None:
        if current_heading is None:
            return
        field_name = ISSUE_FORM_FIELD_ALIASES.get(normalize_key(current_heading))
        if field_name is None:
            return
        value = form_field_value(field_name, current_lines)
        if value:
            metadata[field_name] = value

    for line in body.splitlines():
        heading_match = heading_pattern.match(line)
        if heading_match:
            flush_current_field()
            current_heading = heading_match.group(1).strip()
            current_lines = []
            continue
        if current_heading is not None:
            current_lines.append(line)

    flush_current_field()
    return metadata


def parse_metadata(body: str) -> dict[str, str]:
    """Parse current issue-form metadata owned by Project automation."""

    return parse_issue_form_metadata(body)


def normalize_key(value: str) -> str:
    """Normalize a metadata value for option matching."""

    return re.sub(r"\s+", " ", value.strip().lower())


def issue_form_field_names(body: str) -> tuple[str, ...]:
    """Return supported issue-form metadata field names found in Markdown headings."""

    fields: list[str] = []
    seen: set[str] = set()
    heading_pattern = re.compile(r"^###\s+(.+?)\s*$", re.MULTILINE)
    aliases = {**ISSUE_FORM_FIELD_ALIASES, **LEGACY_NATIVE_BODY_FIELD_ALIASES}

    for match in heading_pattern.finditer(body):
        field_name = aliases.get(normalize_key(match.group(1)))
        if field_name is None or field_name in seen:
            continue
        fields.append(field_name)
        seen.add(field_name)

    return tuple(fields)


def kind_values(value: str) -> tuple[str, ...]:
    """Return normalized kind values from slash, comma, or semicolon separated metadata."""

    values: list[str] = []
    seen: set[str] = set()
    for raw_kind in re.split(r"[/,;]", value):
        kind = normalize_key(raw_kind)
        if not kind or kind in seen:
            continue
        values.append(kind)
        seen.add(kind)
    return tuple(values)


def canonical_metadata(metadata: dict[str, str]) -> dict[str, str]:
    """Convert issue metadata into Project field option names."""

    canonical: dict[str, str] = {}

    priority = metadata.get("Priority")
    if priority:
        canonical[PRIORITY_FIELD] = PRIORITY_ALIASES.get(normalize_key(priority), priority.strip())

    size = metadata.get("Size")
    if size:
        canonical[SIZE_FIELD] = size.strip().upper()

    status = metadata.get("Suggested status")
    if status:
        canonical[STATUS_FIELD] = STATUS_ALIASES.get(normalize_key(status), status.strip())

    return canonical


def remove_project_field(client: GitHubClient, field_name: str) -> bool:
    """Remove one Project field and return whether it existed."""

    project = get_project(client)
    field = project.fields.get(field_name)
    if field is None:
        print(f"Project field '{field_name}' was not found; no cleanup needed")
        return False

    client.graphql(
        """
        mutation($fieldId: ID!) {
          deleteProjectV2Field(input: {fieldId: $fieldId}) {
            clientMutationId
          }
        }
        """,
        {"fieldId": field.id},
    )
    print(f"Removed Project field '{field_name}'")
    return True


def get_project(client: GitHubClient) -> Project:
    """Fetch the configured user-owned Project and its fields."""

    data = client.graphql(
        """
        query($owner: String!, $number: Int!) {
          user(login: $owner) {
            projectV2(number: $number) {
              id
              title
              fields(first: 50) {
                nodes {
                  ... on ProjectV2FieldCommon {
                    id
                    name
                  }
                  ... on ProjectV2SingleSelectField {
                    options {
                      id
                      name
                    }
                  }
                }
              }
            }
          }
        }
        """,
        {"owner": PROJECT_OWNER, "number": PROJECT_NUMBER},
    )
    project_data = data["user"]["projectV2"]
    if project_data is None:
        raise ProjectAutomationError(f"Project {PROJECT_OWNER}/{PROJECT_NUMBER} was not found")

    fields: dict[str, ProjectField] = {}
    for node in project_data["fields"]["nodes"]:
        if node is None:
            continue
        options = {option["name"]: option["id"] for option in node.get("options", [])}
        fields[node["name"]] = ProjectField(node["id"], node["name"], options)

    return Project(project_data["id"], project_data["title"], fields)


def list_project_items(client: GitHubClient) -> list[ProjectItem]:
    """Return all issue items from the configured Project."""

    items: list[ProjectItem] = []
    cursor: str | None = None
    while True:
        data = client.graphql(
            """
            query($owner: String!, $number: Int!, $cursor: String) {
              user(login: $owner) {
                projectV2(number: $number) {
                  items(first: 100, after: $cursor) {
                    pageInfo {
                      hasNextPage
                      endCursor
                    }
                    nodes {
                      id
                      isArchived
                      content {
                        ... on Issue {
                          number
                          title
                          state
                          url
                          milestone {
                            title
                          }
                        }
                      }
                      fieldValues(first: 50) {
                        nodes {
                          ... on ProjectV2ItemFieldSingleSelectValue {
                            name
                            field {
                              ... on ProjectV2FieldCommon {
                                name
                              }
                            }
                          }
                          ... on ProjectV2ItemFieldTextValue {
                            text
                            field {
                              ... on ProjectV2FieldCommon {
                                name
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            """,
            {"owner": PROJECT_OWNER, "number": PROJECT_NUMBER, "cursor": cursor},
        )
        project_items = data["user"]["projectV2"]["items"]
        for node in project_items["nodes"]:
            content = node.get("content")
            if not content:
                continue
            fields: dict[str, str] = {}
            for value in node["fieldValues"]["nodes"]:
                field = value.get("field")
                if not field:
                    continue
                fields[field["name"]] = value.get("name") or value.get("text") or ""
            items.append(ProjectItem(
                id=node["id"],
                number=content.get("number"),
                title=content.get("title", ""),
                url=content.get("url"),
                state=content.get("state"),
                milestone=content["milestone"]["title"] if content.get("milestone") else None,
                archived=node["isArchived"],
                fields=fields,
            ))
        if not project_items["pageInfo"]["hasNextPage"]:
            return items
        cursor = project_items["pageInfo"]["endCursor"]


def project_issue_item(client: GitHubClient, project: Project, issue: Issue) -> ProjectIssueItem | None:
    """Return the Project item for an issue, including archived items."""

    data = client.graphql(
        """
        query($issueId: ID!) {
          node(id: $issueId) {
            ... on Issue {
              projectItems(first: 50, includeArchived: true) {
                nodes {
                  id
                  isArchived
                  project {
                    id
                    title
                  }
                  fieldValues(first: 50) {
                    nodes {
                      ... on ProjectV2ItemFieldSingleSelectValue {
                        name
                        field {
                          ... on ProjectV2FieldCommon {
                            name
                          }
                        }
                      }
                      ... on ProjectV2ItemFieldTextValue {
                        text
                        field {
                          ... on ProjectV2FieldCommon {
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        """,
        {"issueId": issue.node_id},
    )
    for node in data["node"]["projectItems"]["nodes"]:
        if node["project"]["id"] == project.id:
            fields: dict[str, str] = {}
            for value in node["fieldValues"]["nodes"]:
                field = value.get("field")
                if not field:
                    continue
                fields[field["name"]] = value.get("name") or value.get("text") or ""
            return ProjectIssueItem(id=node["id"], archived=node["isArchived"], fields=fields)
    return None


def project_item_id(client: GitHubClient, project: Project, issue: Issue) -> str | None:
    """Return the Project item ID for an issue, if it is already in the Project."""

    item = project_issue_item(client, project, issue)
    return item.id if item else None


def add_issue_to_project(client: GitHubClient, project: Project, issue: Issue) -> str:
    """Add an issue to the Project and return the Project item ID."""

    existing = project_item_id(client, project, issue)
    if existing:
        return existing

    data = client.graphql(
        """
        mutation($projectId: ID!, $contentId: ID!) {
          addProjectV2ItemById(input: { projectId: $projectId, contentId: $contentId }) {
            item {
              id
            }
          }
        }
        """,
        {"projectId": project.id, "contentId": issue.node_id},
    )
    return data["addProjectV2ItemById"]["item"]["id"]


def archive_project_item(client: GitHubClient, project: Project, item_id: str) -> None:
    """Archive one Project item."""

    client.graphql(
        """
        mutation($projectId: ID!, $itemId: ID!) {
          archiveProjectV2Item(input: {projectId: $projectId, itemId: $itemId}) {
            item {
              id
            }
          }
        }
        """,
        {"projectId": project.id, "itemId": item_id},
    )


def unarchive_project_item(client: GitHubClient, project: Project, item_id: str) -> None:
    """Unarchive one Project item."""

    client.graphql(
        """
        mutation($projectId: ID!, $itemId: ID!) {
          unarchiveProjectV2Item(input: {projectId: $projectId, itemId: $itemId}) {
            item {
              id
            }
          }
        }
        """,
        {"projectId": project.id, "itemId": item_id},
    )


def set_single_select_value(client: GitHubClient, project: Project, item_id: str, field: ProjectField, option_id: str) -> None:
    """Set one Project single-select value."""

    client.graphql(
        """
        mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
          updateProjectV2ItemFieldValue(input: {
            projectId: $projectId,
            itemId: $itemId,
            fieldId: $fieldId,
            value: { singleSelectOptionId: $optionId }
          }) {
            projectV2Item {
              id
            }
          }
        }
        """,
        {
            "projectId": project.id,
            "itemId": item_id,
            "fieldId": field.id,
            "optionId": option_id,
        },
    )


def set_issue_status(client: GitHubClient, repository: str, issue_number: int, status_name: str) -> None:
    """Set the roadmap Project status for one issue."""

    issue = get_issue(client, repository, issue_number)
    project = get_project(client)
    field = project.fields.get(STATUS_FIELD)
    if field is None:
        raise ProjectAutomationError(f"Project field '{STATUS_FIELD}' was not found")
    option_id = field.options.get(status_name)
    if option_id is None:
        raise ProjectAutomationError(f"Project status option '{status_name}' was not found")
    item_id = add_issue_to_project(client, project, issue)
    set_single_select_value(client, project, item_id, field, option_id)
    print(f"Set #{issue_number} status to {status_name}")


def sync_issue_archive(client: GitHubClient, repository: str, issue_number: int) -> bool:
    """Sync one issue's archived Project state from its open/closed state."""

    issue = get_issue(client, repository, issue_number)
    project = get_project(client)
    item = project_issue_item(client, project, issue)

    if item is None:
        if issue.state == "open":
            add_issue_to_project(client, project, issue)
            print(f"Added open #{issue.number} to Project; it is visible by default")
            return True
        print(f"::warning::Closed #{issue.number} is not in the Project; cannot archive it")
        return False

    if issue.state == "closed":
        status = item.fields.get(STATUS_FIELD)
        if status != DONE_STATUS:
            visible_status = status or "unset"
            print(
                f"::warning::Closed #{issue.number} has Project status '{visible_status}', "
                f"not '{DONE_STATUS}'; not archiving"
            )
            return False
        if item.archived:
            print(f"#{issue.number} is already archived")
            return False
        archive_project_item(client, project, item.id)
        print(f"Archived #{issue.number} from Project")
        return True

    if issue.state == "open":
        if not item.archived:
            print(f"#{issue.number} is already visible in Project")
            return False
        unarchive_project_item(client, project, item.id)
        print(f"Unarchived #{issue.number} in Project")
        return True

    print(f"::warning::Issue #{issue.number} has unsupported state '{issue.state}'; not changing archive state")
    return False


def ensure_label(client: GitHubClient, repository: str, label: str, color: str, description: str) -> None:
    """Ensure a repository label exists."""

    encoded_label = quote(label, safe="")
    try:
        client.rest("GET", f"/repos/{repository}/labels/{encoded_label}")
        return
    except ProjectAutomationError as error:
        if "GitHub API 404" not in str(error):
            raise

    client.rest(
        "POST",
        f"/repos/{repository}/labels",
        {
            "name": label,
            "color": color,
            "description": description,
        },
    )
    print(f"Created label '{label}'")


def add_issue_label(client: GitHubClient, repository: str, issue_number: int, label: str) -> None:
    """Add one label to an issue."""

    client.rest("POST", f"/repos/{repository}/issues/{issue_number}/labels", {"labels": [label]})


def remove_issue_label(client: GitHubClient, repository: str, issue_number: int, label: str) -> None:
    """Remove one label from an issue."""

    encoded_label = quote(label, safe="")
    try:
        client.rest("DELETE", f"/repos/{repository}/issues/{issue_number}/labels/{encoded_label}")
    except ProjectAutomationError as error:
        if "GitHub API 404" not in str(error):
            raise


def sync_issue(client: GitHubClient, repository: str, issue_number: int, strict: bool) -> bool:
    """Sync one issue's metadata into its milestone and Project fields."""

    issue = get_issue(client, repository, issue_number)
    metadata = parse_metadata(issue.body)
    if not metadata:
        message = f"#{issue.number} has no current issue-form Project metadata; skipping"
        if strict:
            raise ProjectAutomationError(message)
        print(f"::warning::{message}")
        return False

    canonical = canonical_metadata(metadata)
    project = get_project(client)
    item_id = add_issue_to_project(client, project, issue)

    updated = False
    for field_name, option_name in canonical.items():
        field = project.fields.get(field_name)
        if field is None:
            raise ProjectAutomationError(f"Project field '{field_name}' was not found")
        option_id = field.options.get(option_name)
        if option_id is None:
            message = f"Project field '{field_name}' has no option '{option_name}' for #{issue.number}"
            raise ProjectAutomationError(message)
        set_single_select_value(client, project, item_id, field, option_id)
        updated = True
        print(f"Synced #{issue.number}: {field_name} = {option_name}")

    if not updated:
        print(f"::warning::No Project fields were updated for #{issue.number}")
    return updated


def kind_labels_from_metadata(metadata: dict[str, str]) -> tuple[tuple[str, ...], tuple[str, ...]]:
    """Return managed kind labels and unknown kind values represented by issue metadata."""

    kind = metadata.get("Kind")
    if not kind:
        return (), ()

    labels: list[str] = []
    unknown: list[str] = []
    for kind_key in kind_values(kind):
        label = MANAGED_KIND_LABELS.get(kind_key)
        if label:
            labels.append(label[0])
        else:
            unknown.append(kind_key)
    return tuple(labels), tuple(unknown)


def legacy_metadata_reasons(issue: Issue) -> tuple[str, ...]:
    """Return migration reasons for issue metadata that still depends on legacy body fields."""

    reasons: list[str] = []
    legacy_metadata = legacy_metadata_block_fields(issue.body)
    form_fields = set(issue_form_field_names(issue.body))

    def add_reason(reason: str) -> None:
        if reason not in reasons:
            reasons.append(reason)

    if legacy_metadata:
        add_reason("legacy Project metadata block")

    if "Phase" in legacy_metadata:
        add_reason("legacy Phase metadata")
    if "Kind" in legacy_metadata:
        add_reason("legacy Kind metadata")

    project_fields = tuple(
        field for field in (PRIORITY_FIELD, SIZE_FIELD, "Suggested status")
        if field in legacy_metadata
    )
    if project_fields:
        add_reason(f"Project field metadata in legacy block: {', '.join(project_fields)}")

    schedule_fields = tuple(
        field for field in ("Expected start", "Expected deadline")
        if field in legacy_metadata
    )
    if schedule_fields:
        add_reason(f"schedule metadata in legacy block: {', '.join(schedule_fields)}")

    native_form_fields = tuple(
        field for field in ("Milestone", "Kind")
        if field in form_fields
    )
    if native_form_fields:
        add_reason(f"duplicated native issue-form field(s): {', '.join(native_form_fields)}")

    legacy_milestone = legacy_metadata.get("Milestone") or legacy_metadata.get("Phase")
    if legacy_milestone and not issue.milestone:
        add_reason("native milestone missing; body metadata is still the roadmap source")

    managed_labels = {entry[0] for entry in MANAGED_KIND_LABELS.values()}
    target_labels, unknown_kinds = kind_labels_from_metadata(legacy_metadata)
    if (target_labels or unknown_kinds) and not (set(issue.labels) & managed_labels):
        add_reason("managed native label missing; body metadata is still the kind source")

    return tuple(reasons)


def legacy_metadata_issue_numbers(client: GitHubClient, repository: str, args: argparse.Namespace) -> list[int]:
    """Return the issues selected for legacy metadata auditing."""

    selected_modes = sum(
        1 for selected in (
            args.issue_number is not None,
            args.all_open,
            args.all_closed,
            args.all,
        ) if selected
    )
    if selected_modes != 1:
        raise ProjectAutomationError("Provide exactly one of --issue-number, --all-open, --all-closed, or --all")

    if args.issue_number is not None:
        return [args.issue_number]
    if args.all_open:
        return list_open_issues(client, repository)
    if args.all_closed:
        return list_closed_issues(client, repository)
    return list_all_issues(client, repository)


def audit_legacy_metadata_command(args: argparse.Namespace) -> int:
    """Run the audit-legacy-metadata subcommand."""

    client = GitHubClient(token_from_environment())
    issue_numbers = legacy_metadata_issue_numbers(client, args.repo, args)

    findings: list[LegacyMetadataFinding] = []
    failures = 0
    for number in issue_numbers:
        try:
            issue = get_issue(client, args.repo, number)
        except ProjectAutomationError as error:
            failures += 1
            print(f"::error::Failed to inspect #{number}: {error}")
            continue

        reasons = legacy_metadata_reasons(issue)
        if reasons:
            findings.append(LegacyMetadataFinding(issue, reasons))

    for finding in findings:
        reason_text = "; ".join(finding.reasons)
        print(f"::warning::{finding.issue.url} uses legacy metadata: {reason_text}")

    if findings:
        print(f"Found {len(findings)} issue(s) with legacy metadata migration markers.")
    else:
        print("No legacy metadata migration markers found.")

    if failures:
        return 1
    if findings and args.fail_on_findings:
        return 1
    return 0


def sync_labels_for_issue(client: GitHubClient, repository: str, issue_number: int, strict: bool) -> bool:
    """Sync one issue's managed kind labels from its metadata."""

    issue = get_issue(client, repository, issue_number)
    metadata = parse_metadata(issue.body)
    if not metadata:
        message = f"#{issue.number} has no current issue-form Project metadata; skipping label sync"
        if strict:
            raise ProjectAutomationError(message)
        print(f"::warning::{message}")
        return False

    managed_labels = {entry[0] for entry in MANAGED_KIND_LABELS.values()}
    target_labels, unknown_kinds = kind_labels_from_metadata(metadata)
    if not target_labels and not unknown_kinds:
        existing_labels = sorted(set(issue.labels) & managed_labels)
        if existing_labels:
            labels = ", ".join(existing_labels)
            print(f"#{issue.number} has no Kind metadata; keeping existing managed labels: {labels}")
            return False
        message = f"#{issue.number} has no Kind metadata; skipping label sync"
        if strict:
            raise ProjectAutomationError(message)
        print(f"::warning::{message}")
        return False

    if unknown_kinds:
        unknown_list = ", ".join(unknown_kinds)
        message = f"Kind metadata contains unmanaged label values: {unknown_list}"
        if strict:
            raise ProjectAutomationError(message)
        print(f"::warning::{message}")

    target_label_set = set(target_labels)
    if not target_label_set:
        message = f"#{issue.number} has no managed Kind labels to sync"
        if strict:
            raise ProjectAutomationError(message)
        print(f"::warning::{message}")
        return False

    for target_label in target_labels:
        label_name, color, description = MANAGED_KIND_LABELS[target_label]
        ensure_label(client, repository, label_name, color, description)

    changed = False
    current_labels = set(issue.labels)
    for stale_label in sorted((current_labels & managed_labels) - target_label_set):
        remove_issue_label(client, repository, issue.number, stale_label)
        print(f"Removed stale managed label '{stale_label}' from #{issue.number}")
        changed = True

    for label_name in sorted(target_label_set - current_labels):
        add_issue_label(client, repository, issue.number, label_name)
        print(f"Added label '{label_name}' to #{issue.number}")
        changed = True

    if not changed:
        labels = ", ".join(sorted(target_label_set))
        print(f"#{issue.number} already has managed labels: {labels}")
    return changed


def issue_reference_numbers(repository: str, text: str) -> set[int]:
    """Extract same-repository issue references from text."""

    owner, name = repository_parts(repository)
    references: set[int] = set()

    plain_pattern = re.compile(r"(?<![\w/])#(\d+)\b")
    repo_pattern = re.compile(rf"(?<![\w/]){re.escape(owner)}/{re.escape(name)}#(\d+)\b", re.IGNORECASE)
    url_pattern = re.compile(
        rf"https://github\.com/{re.escape(owner)}/{re.escape(name)}/issues/(\d+)\b",
        re.IGNORECASE,
    )

    for pattern in (plain_pattern, repo_pattern, url_pattern):
        references.update(int(match.group(1)) for match in pattern.finditer(text or ""))

    return references


def closing_issue_reference_numbers(repository: str, text: str) -> set[int]:
    """Extract issue references from lines that use GitHub closing keywords."""

    closing_keywords = re.compile(r"\b(close[sd]?|fix(e[sd])?|resolve[sd]?)\b", re.IGNORECASE)
    references: set[int] = set()
    for line in (text or "").splitlines():
        for match in closing_keywords.finditer(line):
            references.update(issue_reference_numbers(repository, line[match.end():]))
    return references


def is_pull_request_reference_error(error: ProjectAutomationError, issue_number: int) -> bool:
    """Return whether an issue lookup failed because the reference is a pull request."""

    return str(error) == f"#{issue_number} is a pull request, not an issue"


def sync_pr_status_command(args: argparse.Namespace) -> int:
    """Run the sync-pr-status subcommand."""

    client = GitHubClient(token_from_environment())
    pull_request = get_pull_request(client, args.repo, args.pr_number)

    if pull_request.draft:
        print(f"PR #{pull_request.number} is a draft; not changing issue status")
        return 0

    if pull_request.merged:
        targets = closing_issue_reference_numbers(args.repo, pull_request.body)
        if not targets:
            print(f"::warning::PR #{pull_request.number} was merged but has no closing issue references")
            return 0
        target_status = "Done"
    else:
        targets = issue_reference_numbers(args.repo, pull_request.body)
        if not targets:
            print(f"::warning::PR #{pull_request.number} has no issue references")
            return 0
        target_status = "In Review"

    for issue_number in sorted(targets):
        try:
            set_issue_status(client, args.repo, issue_number, target_status)
        except ProjectAutomationError as error:
            if is_pull_request_reference_error(error, issue_number):
                print(f"::warning::Skipping #{issue_number} because it is a pull request, not an issue")
                continue
            raise
        if target_status == DONE_STATUS:
            sync_issue_archive(client, args.repo, issue_number)
    return 0


def sync_issue_command(args: argparse.Namespace) -> int:
    """Run the sync-issue subcommand."""

    client = GitHubClient(token_from_environment())

    issue_numbers: list[int]
    if args.all_open:
        issue_numbers = list_open_issues(client, args.repo)
    elif args.issue_number is not None:
        issue_numbers = [args.issue_number]
    else:
        raise ProjectAutomationError("Provide --issue-number or --all-open")

    failures = 0
    for number in issue_numbers:
        try:
            sync_issue(client, args.repo, number, args.strict)
        except ProjectAutomationError as error:
            failures += 1
            print(f"::error::Failed to sync #{number}: {error}")
            if args.strict:
                break

    return 1 if failures else 0


def sync_issue_archive_command(args: argparse.Namespace) -> int:
    """Run the sync-issue-archive subcommand."""

    client = GitHubClient(token_from_environment())

    issue_numbers: list[int]
    selected_modes = sum(1 for selected in (args.issue_number is not None, args.all_open, args.all_closed) if selected)
    if selected_modes != 1:
        raise ProjectAutomationError("Provide exactly one of --issue-number, --all-open, or --all-closed")
    if args.issue_number is not None:
        issue_numbers = [args.issue_number]
    elif args.all_open:
        issue_numbers = list_open_issues(client, args.repo)
    else:
        issue_numbers = list_closed_issues(client, args.repo)

    failures = 0
    for number in issue_numbers:
        try:
            sync_issue_archive(client, args.repo, number)
        except ProjectAutomationError as error:
            failures += 1
            print(f"::error::Failed to sync archive state for #{number}: {error}")

    return 1 if failures else 0


def sync_labels_command(args: argparse.Namespace) -> int:
    """Run the sync-labels subcommand."""

    client = GitHubClient(token_from_environment())

    issue_numbers: list[int]
    if args.all_open:
        issue_numbers = list_open_issues(client, args.repo)
    elif args.issue_number is not None:
        issue_numbers = [args.issue_number]
    else:
        raise ProjectAutomationError("Provide --issue-number or --all-open")

    failures = 0
    for number in issue_numbers:
        try:
            sync_labels_for_issue(client, args.repo, number, args.strict)
        except ProjectAutomationError as error:
            failures += 1
            print(f"::error::Failed to sync labels for #{number}: {error}")
            if args.strict:
                break

    return 1 if failures else 0


def phase_number_from_text(text: str) -> int | None:
    """Extract a roadmap phase number from text."""

    match = re.search(r"\bPhase\s+(\d+)\b", text, re.IGNORECASE)
    return int(match.group(1)) if match else None


def current_focus_phase(plan_text: str) -> int | None:
    """Return the phase number from PLAN.md current focus."""

    match = re.search(r"^Current focus:\s*(.+)$", plan_text, re.MULTILINE)
    return phase_number_from_text(match.group(1)) if match else None


def readme_focus_phase(readme_text: str) -> int | None:
    """Return the phase number from README current focus."""

    match = re.search(r"^Current focus:\s*\*\*(.+?)\*\*\.", readme_text, re.MULTILINE)
    return phase_number_from_text(match.group(1)) if match else None


def phase_statuses(plan_text: str) -> dict[int, str]:
    """Parse PLAN.md phase status table."""

    statuses: dict[int, str] = {}
    pattern = re.compile(r"^\|\s*(\d+)\.\s+[^|]+\|\s*([^|]+?)\s*\|", re.MULTILINE)
    for match in pattern.finditer(plan_text):
        statuses[int(match.group(1))] = match.group(2).strip()
    return statuses


def immediate_next_steps(plan_text: str) -> list[str]:
    """Parse PLAN.md immediate next steps."""

    match = re.search(r"^## Immediate Next Steps\s*(.+)$", plan_text, re.MULTILINE | re.DOTALL)
    if not match:
        return []
    steps: list[str] = []
    for line in match.group(1).splitlines():
        step_match = re.match(r"^\d+\.\s+(.+?)\s*$", line)
        if step_match:
            steps.append(step_match.group(1))
    return steps


def terms(text: str) -> set[str]:
    """Extract normalized search terms for loose issue matching."""

    return {
        token
        for token in re.findall(r"[a-zA-Z][a-zA-Z0-9]+", text.lower())
        if len(token) > 2 and token not in STOPWORDS
    }


def best_issue_match(step: str, items: list[ProjectItem]) -> ProjectItem | None:
    """Find a likely issue for an immediate next step."""

    step_terms = terms(step)
    best_item: ProjectItem | None = None
    best_score = 0
    for item in items:
        if item.state != "OPEN":
            continue
        score = len(step_terms & terms(item.title))
        if score > best_score:
            best_score = score
            best_item = item
    return best_item if best_score >= 2 else None


def check_plan_drift_command(args: argparse.Namespace) -> int:
    """Run the check-plan-drift subcommand."""

    client = GitHubClient(token_from_environment())
    plan_text = Path(args.plan).read_text(encoding="utf-8")
    readme_text = Path(args.readme).read_text(encoding="utf-8") if args.readme else ""
    items = list_project_items(client)

    errors: list[str] = []
    warnings: list[str] = []
    notices: list[str] = []

    plan_focus = current_focus_phase(plan_text)
    readme_focus = readme_focus_phase(readme_text) if readme_text else None
    if plan_focus is None:
        errors.append("PLAN.md does not declare a current focus phase")
    if readme_text and readme_focus is None:
        warnings.append("README.md does not declare a current focus phase")
    if plan_focus is not None and readme_focus is not None and plan_focus != readme_focus:
        errors.append(f"README current focus Phase {readme_focus} does not match PLAN.md Phase {plan_focus}")

    if plan_focus is not None:
        focus_milestone = PHASE_NUMBER_TO_MILESTONE.get(plan_focus)
        if focus_milestone is None:
            notices.append(f"PLAN.md current focus Phase {plan_focus} is not tied to one roadmap milestone")
        else:
            active_focus_items = [
                item for item in items
                if item.milestone == focus_milestone and item.fields.get(STATUS_FIELD) in ACTIVE_STATUSES
            ]
            in_progress_focus_items = [
                item for item in active_focus_items
                if item.fields.get(STATUS_FIELD) == "In Progress"
            ]
            if not active_focus_items:
                errors.append(f"No active Project item found for PLAN.md current focus Phase {plan_focus}")
            elif not in_progress_focus_items:
                warnings.append(f"PLAN.md current focus Phase {plan_focus} has active items but none marked In Progress")
            else:
                labels = ", ".join(f"#{item.number} {item.title}" for item in in_progress_focus_items)
                notices.append(f"Current focus is represented by {labels}")

    statuses = phase_statuses(plan_text)
    for phase, status in statuses.items():
        if status != "Complete":
            continue
        phase_milestone = PHASE_NUMBER_TO_MILESTONE.get(phase)
        if not phase_milestone:
            continue
        if phase_milestone in SHARED_PHASE_MILESTONES:
            continue
        stale_items = [
            item for item in items
            if item.milestone == phase_milestone
            and item.fields.get(PRIORITY_FIELD) == HIGH_PRIORITY
            and item.fields.get(STATUS_FIELD) != DONE_STATUS
        ]
        for item in stale_items:
            warnings.append(f"Phase {phase} is complete in PLAN.md but #{item.number} is still non-done P1 work")

    for step in immediate_next_steps(plan_text):
        match = best_issue_match(step, items)
        if match:
            notices.append(f"Immediate step maps to #{match.number}: {match.title}")
        else:
            notices.append(f"No direct issue match found for immediate step: {step}")

    for message in notices:
        print(f"::notice::{message}")
    for message in warnings:
        print(f"::warning::{message}")
    for message in errors:
        print(f"::error::{message}")

    if errors:
        return 1
    if warnings and args.fail_on_warning:
        return 1
    return 0


def remove_legacy_phase_field_command(args: argparse.Namespace) -> int:
    """Run the remove-legacy-phase-field subcommand."""

    if not args.confirm:
        raise ProjectAutomationError(
            "Refusing to remove the legacy Project Phase field without --confirm. "
            "Run this only when the Project should not expose the duplicate Phase field."
        )

    client = GitHubClient(token_from_environment())
    remove_project_field(client, LEGACY_PHASE_FIELD)
    return 0


def remove_legacy_kind_field_command(args: argparse.Namespace) -> int:
    """Run the remove-legacy-kind-field subcommand."""

    if not args.confirm:
        raise ProjectAutomationError(
            "Refusing to remove the legacy Project Kind field without --confirm. "
            "Run this only when issue labels are the source of truth for kind metadata."
        )

    client = GitHubClient(token_from_environment())
    remove_project_field(client, LEGACY_KIND_FIELD)
    return 0


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""

    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    sync_parser = subparsers.add_parser("sync-issue", help="Sync issue metadata into milestones and Project fields")
    sync_parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY"), help="Repository in owner/name form")
    sync_parser.add_argument("--issue-number", type=int, help="Issue number to sync")
    sync_parser.add_argument("--all-open", action="store_true", help="Sync all open issues")
    sync_parser.add_argument("--strict", action="store_true", help="Fail on missing or invalid issue metadata")
    sync_parser.set_defaults(func=sync_issue_command)

    pr_parser = subparsers.add_parser("sync-pr-status", help="Sync Project issue status from pull request state")
    pr_parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY"), help="Repository in owner/name form")
    pr_parser.add_argument("--pr-number", type=int, required=True, help="Pull request number to inspect")
    pr_parser.set_defaults(func=sync_pr_status_command)

    labels_parser = subparsers.add_parser("sync-labels", help="Sync managed issue labels from metadata")
    labels_parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY"), help="Repository in owner/name form")
    labels_parser.add_argument("--issue-number", type=int, help="Issue number to sync")
    labels_parser.add_argument("--all-open", action="store_true", help="Sync labels for all open issues")
    labels_parser.add_argument("--strict", action="store_true", help="Fail on missing or invalid issue metadata")
    labels_parser.set_defaults(func=sync_labels_command)

    audit_parser = subparsers.add_parser(
        "audit-legacy-metadata",
        help="Report issues that still contain legacy body metadata",
    )
    audit_parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY"), help="Repository in owner/name form")
    audit_parser.add_argument("--issue-number", type=int, help="Issue number to inspect")
    audit_parser.add_argument("--all-open", action="store_true", help="Inspect all open issues")
    audit_parser.add_argument("--all-closed", action="store_true", help="Inspect all closed issues")
    audit_parser.add_argument("--all", action="store_true", help="Inspect all issues")
    audit_parser.add_argument(
        "--fail-on-findings",
        action="store_true",
        help="Exit non-zero when legacy metadata is found",
    )
    audit_parser.set_defaults(func=audit_legacy_metadata_command)

    archive_parser = subparsers.add_parser(
        "sync-issue-archive",
        help="Archive closed Done issues and unarchive open issues in the Project",
    )
    archive_parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY"), help="Repository in owner/name form")
    archive_parser.add_argument("--issue-number", type=int, help="Issue number to sync")
    archive_parser.add_argument("--all-open", action="store_true", help="Sync archive state for all open issues")
    archive_parser.add_argument("--all-closed", action="store_true", help="Sync archive state for all closed issues")
    archive_parser.set_defaults(func=sync_issue_archive_command)

    drift_parser = subparsers.add_parser("check-plan-drift", help="Check PLAN.md and Project state alignment")
    drift_parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY"), help="Repository in owner/name form")
    drift_parser.add_argument("--plan", default="PLAN.md", help="Path to PLAN.md")
    drift_parser.add_argument("--readme", default="README.md", help="Path to README.md")
    drift_parser.add_argument("--fail-on-warning", action="store_true", help="Exit non-zero when warnings are found")
    drift_parser.set_defaults(func=check_plan_drift_command)

    cleanup_parser = subparsers.add_parser(
        "remove-legacy-phase-field",
        help="Remove the legacy custom Project Phase field after milestone migration",
    )
    cleanup_parser.add_argument(
        "--confirm",
        action="store_true",
        help="Confirm that the duplicate Project Phase field should be removed",
    )
    cleanup_parser.set_defaults(func=remove_legacy_phase_field_command)

    kind_cleanup_parser = subparsers.add_parser(
        "remove-legacy-kind-field",
        help="Remove the legacy custom Project Kind field after label migration",
    )
    kind_cleanup_parser.add_argument(
        "--confirm",
        action="store_true",
        help="Confirm that issue labels should be the only Kind projection",
    )
    kind_cleanup_parser.set_defaults(func=remove_legacy_kind_field_command)

    return parser


def main() -> int:
    """Run the selected automation command."""

    parser = build_parser()
    args = parser.parse_args()
    if hasattr(args, "repo") and not args.repo:
        parser.error("--repo is required when GITHUB_REPOSITORY is not set")
    try:
        return args.func(args)
    except ProjectAutomationError as error:
        print(f"::error::{error}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
