#!/usr/bin/env python3
"""Sync issue-form scheduling metadata into GitHub Project date fields."""

from __future__ import annotations

import argparse
import os
import re
import sys
from datetime import date

from .board import (
    add_issue_to_project,
    get_project,
    set_date_value,
)
from ..github import (
    GitHubClient,
    Project,
    ProjectAutomationError,
    ProjectField,
    get_issue,
    list_open_issues,
    token_from_environment,
)

START_DATE_FIELD = os.environ.get("PROJECT_START_DATE_FIELD", "Start date")
END_DATE_FIELD = os.environ.get("PROJECT_END_DATE_FIELD", "End date")
NO_RESPONSE = "_No response_"

SCHEDULE_FIELD_ALIASES = {
    "expected start": "Expected start",
    "start date": "Expected start",
    "starting date": "Expected start",
    "expected deadline": "Expected deadline",
    "deadline": "Expected deadline",
    "end date": "Expected deadline",
    "finish date": "Expected deadline",
    "target date": "Expected deadline",
}


class ProjectScheduleError(RuntimeError):
    """Raised when schedule metadata cannot be synchronized safely."""


def normalize_key(value: str) -> str:
    """Normalize a metadata heading for matching."""

    return re.sub(r"\s+", " ", value.strip().lower())


def form_field_value(lines: list[str]) -> str | None:
    """Return the first non-empty value from an issue-form field body."""

    value = "\n".join(lines).strip()
    if not value or value == NO_RESPONSE:
        return None
    return value.splitlines()[0].strip()


def parse_issue_form_schedule(body: str) -> dict[str, str]:
    """Parse schedule metadata from Markdown generated by GitHub issue forms."""

    metadata: dict[str, str] = {}
    current_heading: str | None = None
    current_lines: list[str] = []
    heading_pattern = re.compile(r"^###\s+(.+?)\s*$")

    def flush_current_field() -> None:
        if current_heading is None:
            return
        field_name = SCHEDULE_FIELD_ALIASES.get(normalize_key(current_heading))
        if field_name is None:
            return
        value = form_field_value(current_lines)
        if value:
            metadata[field_name] = value

    for line in body.splitlines():
        heading_match = heading_pattern.match(line)
        if heading_match:
            flush_current_field()
            current_heading = heading_match.group(1).strip()
            current_lines = []
            continue
        if current_heading is not None:
            current_lines.append(line)

    flush_current_field()
    return metadata


def parse_schedule(body: str) -> dict[str, str]:
    """Parse schedule metadata from current issue-form fields."""

    return parse_issue_form_schedule(body)


def iso_date(value: str, field_name: str) -> str:
    """Validate and normalize a YYYY-MM-DD date value."""

    try:
        parsed = date.fromisoformat(value.strip())
    except ValueError as error:
        raise ProjectScheduleError(f"{field_name} must use YYYY-MM-DD format, got '{value}'") from error
    return parsed.isoformat()


def normalized_schedule(metadata: dict[str, str]) -> dict[str, str]:
    """Return validated schedule values keyed by Project date field name."""

    schedule: dict[str, str] = {}
    start = metadata.get("Expected start")
    deadline = metadata.get("Expected deadline")

    if start:
        schedule[START_DATE_FIELD] = iso_date(start, "Expected start")
    if deadline:
        schedule[END_DATE_FIELD] = iso_date(deadline, "Expected deadline")

    if START_DATE_FIELD in schedule and END_DATE_FIELD in schedule:
        if date.fromisoformat(schedule[START_DATE_FIELD]) > date.fromisoformat(schedule[END_DATE_FIELD]):
            raise ProjectScheduleError("Expected start must not be later than Expected deadline")

    return schedule


def project_date_field(project: Project, field_name: str) -> ProjectField:
    """Return one Project date field by name, or fail with setup guidance."""

    field = project.fields.get(field_name)
    if field is None:
        raise ProjectScheduleError(
            f"Project field '{field_name}' was not found. "
            "Create the date field in the roadmap Project or adjust PROJECT_START_DATE_FIELD/PROJECT_END_DATE_FIELD."
        )
    return field


def sync_issue_schedule(client: GitHubClient, repository: str, issue_number: int, strict: bool) -> bool:
    """Sync one issue's schedule metadata into Project date fields."""

    try:
        issue = get_issue(client, repository, issue_number)
    except ProjectAutomationError as error:
        raise ProjectScheduleError(str(error)) from error

    schedule = normalized_schedule(parse_schedule(issue.body))
    if not schedule:
        message = f"#{issue.number} has no Expected start or Expected deadline metadata; skipping schedule sync"
        if strict:
            raise ProjectScheduleError(message)
        print(f"::notice::{message}")
        return False

    try:
        project = get_project(client)
        item_id = add_issue_to_project(client, project, issue)
    except ProjectAutomationError as error:
        raise ProjectScheduleError(str(error)) from error

    for field_name, value in schedule.items():
        field = project_date_field(project, field_name)
        try:
            set_date_value(client, project, item_id, field, value)
        except ProjectAutomationError as error:
            raise ProjectScheduleError(str(error)) from error
        print(f"Synced #{issue.number}: {field_name} = {value}")

    return True


def issue_numbers_for_args(client: GitHubClient, repository: str, args: argparse.Namespace) -> list[int]:
    """Return selected issue numbers for the current invocation."""

    if args.all_open and args.issue_number is not None:
        raise ProjectScheduleError("Provide --issue-number or --all-open, not both")
    if args.all_open:
        try:
            return list_open_issues(client, repository)
        except ProjectAutomationError as error:
            raise ProjectScheduleError(str(error)) from error
    if args.issue_number is not None:
        return [args.issue_number]
    raise ProjectScheduleError("Provide --issue-number or --all-open")


def sync_schedule_command(args: argparse.Namespace) -> int:
    """Run schedule synchronization."""

    client = GitHubClient(token_from_environment())
    issue_numbers = issue_numbers_for_args(client, args.repo, args)

    failures = 0
    for number in issue_numbers:
        try:
            sync_issue_schedule(client, args.repo, number, args.strict)
        except ProjectScheduleError as error:
            failures += 1
            print(f"::error::Failed to sync schedule for #{number}: {error}")
            if args.strict:
                break

    return 1 if failures else 0


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY"), help="Repository in owner/name form")
    parser.add_argument("--issue-number", type=int, help="Issue number to sync")
    parser.add_argument("--all-open", action="store_true", help="Sync every open issue with schedule metadata")
    parser.add_argument("--strict", action="store_true", help="Fail on missing or invalid schedule metadata")
    return parser


def main() -> int:
    """Run the schedule sync command."""

    parser = build_parser()
    args = parser.parse_args()
    if not args.repo:
        parser.error("--repo is required when GITHUB_REPOSITORY is not set")
    try:
        return sync_schedule_command(args)
    except ProjectScheduleError as error:
        print(f"::error::{error}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
