package compiler;

/// Origin category for a Nova source file.
///
/// The origin is intentionally metadata only. It helps the project pipeline
/// distinguish user files from in-memory snippets and future standard-library
/// inputs without changing parser or semantic behavior.
public enum SourceOrigin {

    /// Source loaded from the local filesystem.
    DISK,

    /// Source provided directly by a caller, usually tests or tools.
    MEMORY,

    /// Source that will later come from Nova standard-library packages.
    STANDARD_LIBRARY,

    /// Source generated by tooling before it enters the compiler pipeline.
    GENERATED
}
