#!/usr/bin/env python3
"""Issue metadata parsing and sync helpers for Nova Project automation."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from urllib.parse import quote

from .project_board import add_issue_to_project, get_project, set_single_select_value
from .project_github import (
    GitHubClient,
    Issue,
    ProjectAutomationError,
    get_issue,
    list_all_issues,
    list_closed_issues,
    list_open_issues,
)
from .project_metadata import (
    MANAGED_KIND_LABELS,
    METADATA_HEADER,
    NO_RESPONSE,
    PRIORITY_ALIASES,
    PRIORITY_FIELD,
    SIZE_FIELD,
    STATUS_ALIASES,
    STATUS_FIELD,
)


ISSUE_FORM_FIELD_ALIASES = {
    "priority": "Priority",
    "size": "Size",
    "suggested status": "Suggested status",
    "area": "Area",
}

LEGACY_NATIVE_BODY_FIELD_ALIASES = {
    "milestone": "Milestone",
    "labels": "Kind",
    "label": "Kind",
    "kind": "Kind",
}


@dataclass(frozen=True)
class LegacyMetadataFinding:
    """One issue that still carries metadata migration markers."""

    issue: Issue
    reasons: tuple[str, ...]


def legacy_metadata_block_fields(body: str) -> dict[str, str]:
    """Return fields from a legacy Project metadata block for migration audits."""

    metadata: dict[str, str] = {}
    in_block = False
    header_pattern = re.compile(r"^##\s+(.+?)\s*$")
    item_pattern = re.compile(r"^-\s*([^:]+):\s*(.*?)\s*$")

    for line in body.splitlines():
        header_match = header_pattern.match(line)
        if header_match:
            heading = header_match.group(1).strip()
            if heading == METADATA_HEADER:
                in_block = True
                continue
            if in_block:
                break

        if not in_block:
            continue

        item_match = item_pattern.match(line)
        if item_match:
            metadata[item_match.group(1).strip()] = item_match.group(2).strip()

    return metadata


def form_field_value(field_name: str, lines: list[str]) -> str | None:
    """Return one metadata value from an issue-form field body."""

    checked_values: list[str] = []
    saw_checkbox = False
    for line in lines:
        checkbox = re.match(r"^-\s*\[([ xX])\]\s*(.+?)\s*$", line)
        if not checkbox:
            continue
        saw_checkbox = True
        if checkbox.group(1).lower() == "x":
            checked_values.append(checkbox.group(2).strip())

    if checked_values:
        return " / ".join(checked_values)
    if saw_checkbox and field_name == "Kind":
        return None

    value = "\n".join(lines).strip()
    if not value or value == NO_RESPONSE:
        return None
    return value.splitlines()[0].strip()


def parse_issue_form_metadata(body: str) -> dict[str, str]:
    """Parse metadata from Markdown generated by GitHub issue forms."""

    metadata: dict[str, str] = {}
    current_heading: str | None = None
    current_lines: list[str] = []
    heading_pattern = re.compile(r"^###\s+(.+?)\s*$")

    def flush_current_field() -> None:
        if current_heading is None:
            return
        field_name = ISSUE_FORM_FIELD_ALIASES.get(normalize_key(current_heading))
        if field_name is None:
            return
        value = form_field_value(field_name, current_lines)
        if value:
            metadata[field_name] = value

    for line in body.splitlines():
        heading_match = heading_pattern.match(line)
        if heading_match:
            flush_current_field()
            current_heading = heading_match.group(1).strip()
            current_lines = []
            continue
        if current_heading is not None:
            current_lines.append(line)

    flush_current_field()
    return metadata


def parse_metadata(body: str) -> dict[str, str]:
    """Parse current issue-form metadata owned by Project automation."""

    return parse_issue_form_metadata(body)


def normalize_key(value: str) -> str:
    """Normalize a metadata value for option matching."""

    return re.sub(r"\s+", " ", value.strip().lower())


def issue_form_field_names(body: str) -> tuple[str, ...]:
    """Return supported issue-form metadata field names found in Markdown headings."""

    fields: list[str] = []
    seen: set[str] = set()
    heading_pattern = re.compile(r"^###\s+(.+?)\s*$", re.MULTILINE)
    aliases = {**ISSUE_FORM_FIELD_ALIASES, **LEGACY_NATIVE_BODY_FIELD_ALIASES}

    for match in heading_pattern.finditer(body):
        field_name = aliases.get(normalize_key(match.group(1)))
        if field_name is None or field_name in seen:
            continue
        fields.append(field_name)
        seen.add(field_name)

    return tuple(fields)


def kind_values(value: str) -> tuple[str, ...]:
    """Return normalized kind values from slash, comma, or semicolon separated metadata."""

    values: list[str] = []
    seen: set[str] = set()
    for raw_kind in re.split(r"[/,;]", value):
        kind = normalize_key(raw_kind)
        if not kind or kind in seen:
            continue
        values.append(kind)
        seen.add(kind)
    return tuple(values)


def canonical_metadata(metadata: dict[str, str]) -> dict[str, str]:
    """Convert issue metadata into Project field option names."""

    canonical: dict[str, str] = {}

    priority = metadata.get("Priority")
    if priority:
        canonical[PRIORITY_FIELD] = PRIORITY_ALIASES.get(normalize_key(priority), priority.strip())

    size = metadata.get("Size")
    if size:
        canonical[SIZE_FIELD] = size.strip().upper()

    status = metadata.get("Suggested status")
    if status:
        canonical[STATUS_FIELD] = STATUS_ALIASES.get(normalize_key(status), status.strip())

    return canonical


def ensure_label(client: GitHubClient, repository: str, label: str, color: str, description: str) -> None:
    """Ensure a repository label exists."""

    encoded_label = quote(label, safe="")
    try:
        client.rest("GET", f"/repos/{repository}/labels/{encoded_label}")
        return
    except ProjectAutomationError as error:
        if "GitHub API 404" not in str(error):
            raise

    client.rest(
        "POST",
        f"/repos/{repository}/labels",
        {
            "name": label,
            "color": color,
            "description": description,
        },
    )
    print(f"Created label '{label}'")


def add_issue_label(client: GitHubClient, repository: str, issue_number: int, label: str) -> None:
    """Add one label to an issue."""

    client.rest("POST", f"/repos/{repository}/issues/{issue_number}/labels", {"labels": [label]})


def remove_issue_label(client: GitHubClient, repository: str, issue_number: int, label: str) -> None:
    """Remove one label from an issue."""

    encoded_label = quote(label, safe="")
    try:
        client.rest("DELETE", f"/repos/{repository}/issues/{issue_number}/labels/{encoded_label}")
    except ProjectAutomationError as error:
        if "GitHub API 404" not in str(error):
            raise


def sync_issue(client: GitHubClient, repository: str, issue_number: int, strict: bool) -> bool:
    """Sync one issue's metadata into its milestone and Project fields."""

    issue = get_issue(client, repository, issue_number)
    metadata = parse_metadata(issue.body)
    if not metadata:
        message = f"#{issue.number} has no current issue-form Project metadata; skipping"
        if strict:
            raise ProjectAutomationError(message)
        print(f"::warning::{message}")
        return False

    canonical = canonical_metadata(metadata)
    project = get_project(client)
    item_id = add_issue_to_project(client, project, issue)

    updated = False
    for field_name, option_name in canonical.items():
        field = project.fields.get(field_name)
        if field is None:
            raise ProjectAutomationError(f"Project field '{field_name}' was not found")
        option_id = field.options.get(option_name)
        if option_id is None:
            message = f"Project field '{field_name}' has no option '{option_name}' for #{issue.number}"
            raise ProjectAutomationError(message)
        set_single_select_value(client, project, item_id, field, option_id)
        updated = True
        print(f"Synced #{issue.number}: {field_name} = {option_name}")

    if not updated:
        print(f"::warning::No Project fields were updated for #{issue.number}")
    return updated


def kind_labels_from_metadata(metadata: dict[str, str]) -> tuple[tuple[str, ...], tuple[str, ...]]:
    """Return managed kind labels and unknown kind values represented by issue metadata."""

    kind = metadata.get("Kind")
    if not kind:
        return (), ()

    labels: list[str] = []
    unknown: list[str] = []
    for kind_key in kind_values(kind):
        label = MANAGED_KIND_LABELS.get(kind_key)
        if label:
            labels.append(label[0])
        else:
            unknown.append(kind_key)
    return tuple(labels), tuple(unknown)


def legacy_metadata_reasons(issue: Issue) -> tuple[str, ...]:
    """Return migration reasons for issue metadata that still depends on legacy body fields."""

    reasons: list[str] = []
    legacy_metadata = legacy_metadata_block_fields(issue.body)
    form_fields = set(issue_form_field_names(issue.body))

    def add_reason(reason: str) -> None:
        if reason not in reasons:
            reasons.append(reason)

    if legacy_metadata:
        add_reason("legacy Project metadata block")

    if "Phase" in legacy_metadata:
        add_reason("legacy Phase metadata")
    if "Kind" in legacy_metadata:
        add_reason("legacy Kind metadata")

    project_fields = tuple(
        field for field in (PRIORITY_FIELD, SIZE_FIELD, "Suggested status")
        if field in legacy_metadata
    )
    if project_fields:
        add_reason(f"Project field metadata in legacy block: {', '.join(project_fields)}")

    schedule_fields = tuple(
        field for field in ("Expected start", "Expected deadline")
        if field in legacy_metadata
    )
    if schedule_fields:
        add_reason(f"schedule metadata in legacy block: {', '.join(schedule_fields)}")

    native_form_fields = tuple(
        field for field in ("Milestone", "Kind")
        if field in form_fields
    )
    if native_form_fields:
        add_reason(f"duplicated native issue-form field(s): {', '.join(native_form_fields)}")

    legacy_milestone = legacy_metadata.get("Milestone") or legacy_metadata.get("Phase")
    if legacy_milestone and not issue.milestone:
        add_reason("native milestone missing; body metadata is still the roadmap source")

    managed_labels = {entry[0] for entry in MANAGED_KIND_LABELS.values()}
    target_labels, unknown_kinds = kind_labels_from_metadata(legacy_metadata)
    if (target_labels or unknown_kinds) and not (set(issue.labels) & managed_labels):
        add_reason("managed native label missing; body metadata is still the kind source")

    return tuple(reasons)


def legacy_metadata_issue_numbers(client: GitHubClient, repository: str, args: argparse.Namespace) -> list[int]:
    """Return the issues selected for legacy metadata auditing."""

    selected_modes = sum(
        1 for selected in (
            args.issue_number is not None,
            args.all_open,
            args.all_closed,
            args.all,
        ) if selected
    )
    if selected_modes != 1:
        raise ProjectAutomationError("Provide exactly one of --issue-number, --all-open, --all-closed, or --all")

    if args.issue_number is not None:
        return [args.issue_number]
    if args.all_open:
        return list_open_issues(client, repository)
    if args.all_closed:
        return list_closed_issues(client, repository)
    return list_all_issues(client, repository)


def sync_labels_for_issue(client: GitHubClient, repository: str, issue_number: int, strict: bool) -> bool:
    """Sync one issue's managed kind labels from its metadata."""

    issue = get_issue(client, repository, issue_number)
    metadata = parse_metadata(issue.body)
    if not metadata:
        message = f"#{issue.number} has no current issue-form Project metadata; skipping label sync"
        if strict:
            raise ProjectAutomationError(message)
        print(f"::warning::{message}")
        return False

    managed_labels = {entry[0] for entry in MANAGED_KIND_LABELS.values()}
    target_labels, unknown_kinds = kind_labels_from_metadata(metadata)
    if not target_labels and not unknown_kinds:
        existing_labels = sorted(set(issue.labels) & managed_labels)
        if existing_labels:
            labels = ", ".join(existing_labels)
            print(f"#{issue.number} has no Kind metadata; keeping existing managed labels: {labels}")
            return False
        message = f"#{issue.number} has no Kind metadata; skipping label sync"
        if strict:
            raise ProjectAutomationError(message)
        print(f"::warning::{message}")
        return False

    if unknown_kinds:
        unknown_list = ", ".join(unknown_kinds)
        message = f"Kind metadata contains unmanaged label values: {unknown_list}"
        if strict:
            raise ProjectAutomationError(message)
        print(f"::warning::{message}")

    target_label_set = set(target_labels)
    if not target_label_set:
        message = f"#{issue.number} has no managed Kind labels to sync"
        if strict:
            raise ProjectAutomationError(message)
        print(f"::warning::{message}")
        return False

    for target_label in target_labels:
        label_name, color, description = MANAGED_KIND_LABELS[target_label]
        ensure_label(client, repository, label_name, color, description)

    changed = False
    current_labels = set(issue.labels)
    for stale_label in sorted((current_labels & managed_labels) - target_label_set):
        remove_issue_label(client, repository, issue.number, stale_label)
        print(f"Removed stale managed label '{stale_label}' from #{issue.number}")
        changed = True

    for label_name in sorted(target_label_set - current_labels):
        add_issue_label(client, repository, issue.number, label_name)
        print(f"Added label '{label_name}' to #{issue.number}")
        changed = True

    if not changed:
        labels = ", ".join(sorted(target_label_set))
        print(f"#{issue.number} already has managed labels: {labels}")
    return changed
